os: osx
osx_image: xcode11.3

before_install:
  - brew update
  - brew tap osx-cross/avr
  - brew tap osx-cross/arm
  - brew install git doxygen boost gcc avr-gcc arm-gcc-bin cmake || true
  - brew upgrade boost gcc git || true
  - pip3 install --user modm scons
  - export PATH=/Users/travis/Library/Python/3.8/bin:/usr/local/bin:$PATH

script:
  - (cd test && make run-hosted-darwin)
  - (cd examples && ../tools/scripts/examples_compile.py linux)
  - (cd examples && ../tools/scripts/examples_compile.py stm32f1_discovery nucleo_f103rb olimexino_stm32 stm32f103c8t6_blue_pill stm32f103c8t6_black_pill)
  - (cd test && make compile-arduino-nano)
