language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:mapnik/boost
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python3 python-jinja2
 - sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libgtkmm-2.4-dev
 - sudo apt-get install -y gcc-arm-none-eabi g++-4.8
 - sudo apt-get install -y libboost1.49-dev libboost-system1.49-dev libboost-thread1.49-dev
 - export CC=gcc-4.8
 - export CXX=g++-4.8
 - wget http://www.atmel.com/images/avr8-gnu-toolchain-3.4.5.1522-linux.any.x86.tar.gz -O avr8.tar.gz
 - tar -zxf avr8.tar.gz
 - export PATH="$PATH:$TRAVIS_BUILD_DIR/avr8-gnu-toolchain-linux_x86/bin"
script:
 - scons check
 - scons unittest
