name: Run ARM Cortex-M tests on Windows

on: [pull_request]

jobs:
  windows_armcortexm:
    runs-on: windows-2019
    #env:
    #  PYTHONIOENCODING: "utf-8"

    steps:

      # Disabling snake-oil for performance reasons
      - name: Disable Windows Defender
        run: Set-MpPreference -DisableRealtimeMonitoring $true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Python packages
        run: |
          pip install --user modm scons future

      - name: Download ARM Toolchain
        shell: powershell
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -OutFile gcc-arm-none-eabi-win32.zip https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-win32.zip

      - name: Install ARM Toolchain
        shell: powershell
        run: |
          Add-Type -Assembly "System.IO.Compression.Filesystem"
          [System.IO.Compression.ZipFile]::ExtractToDirectory("gcc-arm-none-eabi-win32.zip", "C:\arm-none-eabi-gcc")
          dir C:\arm-none-eabi-gcc
          echo "::add-path::C:\arm-none-eabi-gcc\bin"
          rm gcc-arm-none-eabi-win32.zip

      - name: Show lbuild and arm-none-eabi-gcc Version Information
        run: |
          lbuild --version
          arm-none-eabi-g++ --version

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Git Submodules
        shell: bash
        run: |
          git submodule update --init

      - name: Compile STM32 Examples
        shell: bash
        run: |
          (cd examples && python ../tools/scripts/examples_compile.py nucleo_f031k6 nucleo_f103rb nucleo_f303re nucleo_f411re nucleo_f746zg)
          (cd examples && python ../tools/scripts/examples_compile.py nucleo_g071rb nucleo_l152re nucleo_l476rg nucleo_g474re)

      # - name: Compile AVR Examples
      #   shell: bash
      #   run: |
      #     (cd examples && python ../tools/scripts/examples_compile.py avr)
